### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "java.util.List.isEmpty()" because "strings" is null

### ISSUE THREAD

**Issue by wagulu** [open-obfuscator/dProtect#15]
Unexpected error
java.lang.NullPointerException: Cannot invoke "java.util.List.isEmpty()" because "strings" is null
        at dprotect.obfuscation.strings.StringObfuscator.<init>(StringObfuscator.java:57) ~[dprotect.jar:1.0.0]
        at dprotect.obfuscation.CodeObfuscator.runStringObfuscation(CodeObfuscator.java:171) ~[dprotect.jar:1.0.0]
        at dprotect.obfuscation.CodeObfuscator.obfuscate(CodeObfuscator.java:100) ~[dprotect.jar:1.0.0]
        at dprotect.obfuscation.CodeObfuscator.execute(CodeObfuscator.java:74) ~[dprotect.jar:1.0.0]
        at proguard.pass.PassRunner.run(PassRunner.java:24) ~[dprotect.jar:1.0.0]
        at dprotect.DProtect.obfuscate(DProtect.java:507) ~[dprotect.jar:1.0.0]
        at dprotect.DProtect.execute(DProtect.java:204) ~[dprotect.jar:1.0.0]
        at dprotect.DProtect.main(DProtect.java:664) ~[dprotect.jar:1.0.0]

**Comment by hieunguyen-vkey** [comment]
I got the same issue.

**Comment by hieunguyen-vkey** [comment]
@wagulu 
The root cause is `dprotect-rules.pro` file is empty.
I putted some obfuscate, and it works.

**Comment by ReverseFeng** [comment]
How is this solved？

**Comment by wagulu** [comment]
-obfuscate-strings "xx"
add to your dprotect-rules.pro

**Comment by DDugs** [comment]
can you share your .pro file i think i still have some issues

**Comment by meumeu-dev** [comment]
I hit the same issue and found **two distinct NPE bugs** in dProtect v1.0.0:

### Bug 1 — `StringObfuscator.java:57` (this issue)
When no `-obfuscate-strings` rule is present, `runStringObfuscation()` is still called unconditionally in `CodeObfuscator.obfuscate()` (line 100), and the `strings` list is `null`.

**Fix:**
```java
// StringObfuscator.java constructor
this.strings = strings != null ? strings : Collections.emptyList();
```
Or guard the call in `CodeObfuscator.obfuscate()`:
```java
if (configuration.stringObfuscations != null && !configuration.stringObfuscations.isEmpty()) {
    runStringObfuscation(programClassPool, libraryClassPool);
}
```

### Bug 2 — `StringFieldMarker.java:52` (separate NPE)
Even **with** `-obfuscate-strings` configured, there's a second NPE when processing fields not marked for obfuscation (e.g. fields inherited from Android framework classes):

```
NullPointerException: Cannot read field "encodeStrings" because the return value of
"ObfuscationInfo.getObfuscationInfo(Field)" is null
    at StringFieldMarker.visitFieldrefConstant(StringFieldMarker.java:52)
```

**Fix:**
```java
// StringFieldMarker.visitFieldrefConstant()
ObfuscationInfo info = ObfuscationInfo.getObfuscationInfo(field);
if (info == null) return;  // Skip fields not marked for obfuscation
```

### Reproduction
Any Android app (API 33, javac -source 1.8) with 2+ classes. Bug 2 triggers even with a valid config. Both are trivial null-checks.

I can submit a PR if there's interest — the fixes are 2-3 lines total.
